<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="171" started-at="2022-04-29T15:07:21 IST" finished-at="2022-04-29T15:07:21 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="171" started-at="2022-04-29T15:07:21 IST" finished-at="2022-04-29T15:07:21 IST">
      <class name="Day_11Parameter_Ex.Example_Param5">
        <test-method status="PASS" signature="signIn()[pri:0, instance:Day_11Parameter_Ex.Example_Param5@1f554b06]" name="signIn" duration-ms="24" started-at="2022-04-29T15:07:21 IST" finished-at="2022-04-29T15:07:21 IST">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at Day_11Parameter_Ex.Example_Param5.signIn(Example_Param5.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method status="PASS" signature="login()[pri:0, instance:Day_11Parameter_Ex.Example_Param5@1f554b06]" name="login" duration-ms="3" started-at="2022-04-29T15:07:21 IST" depends-on-methods="Day_11Parameter_Ex.Example_Param5.signIn" finished-at="2022-04-29T15:07:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="checkNotification()[pri:0, instance:Day_11Parameter_Ex.Example_Param5@1f554b06]" name="checkNotification" duration-ms="3" started-at="2022-04-29T15:07:21 IST" depends-on-methods="Day_11Parameter_Ex.Example_Param5.login" finished-at="2022-04-29T15:07:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkNotification -->
      </class> <!-- Day_11Parameter_Ex.Example_Param5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
